#!/bin/bash
# ─────────────────────────────────────────────────────────────
# SVAO Section PR Creator
# Creates PRs for completed sections
# ─────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "$*"; }
log_info() { echo -e "${BLUE}i${NC} $*"; }
log_success() { echo -e "${GREEN}✓${NC} $*"; }
log_warn() { echo -e "${YELLOW}!${NC} $*"; }
log_error() { echo -e "${RED}x${NC} $*" >&2; }

# ─────────────────────────────────────────────────────────────
# PR Creation
# ─────────────────────────────────────────────────────────────

create_section_pr() {
  local prd_file="$1"
  local state_file="$2"
  local section_num="$3"

  # Check if gh is available
  if ! command -v gh &> /dev/null; then
    log_error "GitHub CLI (gh) not found. Install with: brew install gh"
    return 1
  fi

  # Check if authenticated
  if ! gh auth status &> /dev/null; then
    log_error "Not authenticated with GitHub. Run: gh auth login"
    return 1
  fi

  # Get section info
  local section_name
  section_name=$(jq -r --arg n "$section_num" '
    .sections[] | select(.number == ($n | tonumber)) | .name
  ' "$prd_file")

  local change_id
  change_id=$(jq -r '.change_id' "$prd_file")

  # Get completed tasks in section
  local tasks
  tasks=$(jq -r --arg n "$section_num" '
    .sections[] | select(.number == ($n | tonumber)) | .tasks[].id
  ' "$prd_file" | tr '\n' ', ' | sed 's/,$//')

  # Get commits from tasks
  local commits=""
  for task_id in $(jq -r --arg n "$section_num" '
    .sections[] | select(.number == ($n | tonumber)) | .tasks[].id
  ' "$prd_file"); do
    local task_commits
    task_commits=$(jq -r --arg id "$task_id" '.tasks[$id].commits // [] | .[]' "$state_file" 2>/dev/null || echo "")
    commits="$commits $task_commits"
  done

  # Build PR title and body
  local branch_name="svao/${change_id}/section-${section_num}"
  local pr_title="feat(${change_id}): Section ${section_num} - ${section_name}"

  local pr_body
  pr_body=$(cat <<EOF
## Summary

This PR completes Section ${section_num}: **${section_name}** of the ${change_id} feature.

### Tasks Completed
$(jq -r --arg n "$section_num" '
  .sections[] | select(.number == ($n | tonumber)) | .tasks[] | "- [x] \(.id): \(.description)"
' "$prd_file")

### Files Changed
$(jq -r --arg n "$section_num" '
  .sections[] | select(.number == ($n | tonumber)) | .tasks[].files[]
' "$prd_file" | sort -u | sed 's/^/- /')

---

🤖 Generated by SVAO (Self-Validating Agent Orchestra)
EOF
)

  # Check if branch exists, create if not
  if ! git rev-parse --verify "$branch_name" &> /dev/null; then
    log_info "Creating branch: $branch_name"
    git checkout -b "$branch_name"
  else
    git checkout "$branch_name"
  fi

  # Push branch
  log_info "Pushing branch to remote..."
  git push -u origin "$branch_name"

  # Create PR
  log_info "Creating pull request..."
  local pr_url
  pr_url=$(gh pr create \
    --title "$pr_title" \
    --body "$pr_body" \
    --base main 2>&1) || {
    # Check if PR already exists
    if echo "$pr_url" | grep -q "already exists"; then
      log_warn "PR already exists for this branch"
      pr_url=$(gh pr view "$branch_name" --json url -q '.url')
    else
      log_error "Failed to create PR: $pr_url"
      return 1
    fi
  }

  log_success "PR created: $pr_url"

  # Record PR in state
  local tmp_file="${state_file}.tmp.$$"
  jq --arg section "$section_num" --arg url "$pr_url" '
    .section_prs = (.section_prs // {}) |
    .section_prs[$section] = $url
  ' "$state_file" > "$tmp_file"
  mv "$tmp_file" "$state_file"

  # Return to original branch
  git checkout -

  echo "$pr_url"
}

# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

main() {
  local action="${1:-}"

  case "$action" in
    create)
      [[ $# -lt 4 ]] && log_error "Usage: pr-creator.sh create <prd-file> <state-file> <section-num>" && exit 1
      create_section_pr "$2" "$3" "$4"
      ;;
    *)
      echo "Usage: pr-creator.sh <action> [args]"
      echo ""
      echo "Actions:"
      echo "  create <prd> <state> <section>  - Create PR for completed section"
      exit 1
      ;;
  esac
}

main "$@"
